env:
  node: true
  es6: true
extends:
  - standard
plugins:
  - import
rules:
  no-console: warn
  react/no-unused-prop-types: warn
  react/prop-types: warn
  comma-dangle: off

  import/named: error
  import/namespace: error
