language: node_js
node_js:
  - 7
os:
- linux

env:
  - ESLINT_VERSION=4

install:
  - npm install && npm install
  - npm install eslint@$ESLINT_VERSION --ignore-scripts || true

script:
  - "npm test"

after_success:
  - npm run coveralls
